name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  blog:
    runs-on: ubuntu-latest
    name: Fetch and Generate Blog Posts
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Readme Blog Post Action
        uses: ErrorGamer2000/github-readme-blog-post-action@v1
        with:
          feed_urls: "https://blog.justjordant.com/rss.xml"
          show_feed_data: false
      
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save Generated Blog Posts
          skip_checkout: true
        
